# -*- coding: utf-8 -*-
"""html quick styler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cUSrYy50Q70fHvTu63xMkHhJ2y0GhLyn
"""

!pip install -U transformers



# use a pipeline as a high-level helper
from transformers import pipeline
pipe = pipeline("text-generation",model="ibm-granite/granite-3.3-2b-instruct")
messages=[
    {"role": "user","content":"who are you?"}
]
pipe(messages)

# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role": "user", "content": "Who are you?"},
]

inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt",
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

!pip install -q gradio

# ============================================================
# HTML QUICK STYLER – ADVANCED VERSION (ERROR-FREE)
# ============================================================

import re
import random
from datetime import datetime
from typing import Tuple, Dict, List
import gradio as gr

# ============================================================
# COLOR PALETTE GENERATOR
# ============================================================

class ColorPaletteGenerator:
    """Generate visually cohesive color palettes"""

    @staticmethod
    def generate_palette(style: str = "modern") -> Dict[str, str]:
        palettes = {
            "modern": {
                "primary": "#667eea",
                "secondary": "#764ba2",
                "accent": "#f56565",
                "background": "#f7fafc",
                "text": "#2d3748",
                "border": "#e2e8f0"
            },
            "creative": {
                "primary": "#9f7aea",
                "secondary": "#ed64a6",
                "accent": "#38b2ac",
                "background": "#faf5ff",
                "text": "#2d3748",
                "border": "#d6bcfa"
            },
            "minimal": {
                "primary": "#2d3748",
                "secondary": "#4a5568",
                "accent": "#718096",
                "background": "#ffffff",
                "text": "#1a202c",
                "border": "#e2e8f0"
            }
        }
        return palettes.get(style.lower(), palettes["modern"])

# ============================================================
# HTML PAGE BUILDER
# ============================================================

class HTMLPageBuilder:
    """Build styled HTML pages from descriptions"""

    @staticmethod
    def extract_sections(description: str) -> List[str]:
        sections = []
        keywords = {
            "hero": ["hero", "banner", "landing"],
            "features": ["features", "services", "benefits"],
            "about": ["about", "company", "team"],
            "portfolio": ["portfolio", "projects", "gallery"],
            "testimonials": ["testimonials", "reviews", "feedback"],
            "pricing": ["pricing", "plans", "cost"],
            "contact": ["contact", "reach"]
        }

        for section, keys in keywords.items():
            if any(k in description.lower() for k in keys):
                sections.append(section)

        return sections if sections else ["hero", "features", "contact"]

    @staticmethod
    def build_sections(sections: List[str]) -> str:
        html = ""
        for sec in sections:
            html += f"""
            <section class="{sec}">
                <h2>{sec.title()}</h2>
                <p>This is the {sec} section.</p>
            </section>
            """
        return html

# ============================================================
# CSS GENERATOR
# ============================================================

class CSSGenerator:
    @staticmethod
    def generate(palette: Dict[str, str]) -> str:
        return f"""
        <style>
        :root {{
            --primary: {palette['primary']};
            --secondary: {palette['secondary']};
            --accent: {palette['accent']};
            --bg: {palette['background']};
            --text: {palette['text']};
            --border: {palette['border']};
        }}

        body {{
            margin: 0;
            font-family: Arial, sans-serif;
            background: var(--bg);
            color: var(--text);
        }}

        header {{
            padding: 4rem;
            text-align: center;
            background: linear-gradient(135deg, var(--primary), var(--secondary));
            color: white;
        }}

        section {{
            padding: 3rem;
            margin: 2rem auto;
            max-width: 1000px;
            border-bottom: 1px solid var(--border);
        }}

        button {{
            background: var(--accent);
            border: none;
            color: white;
            padding: 12px 20px;
            cursor: pointer;
            transition: 0.3s;
        }}

        button:hover {{
            opacity: 0.85;
        }}
        </style>
        """

# ============================================================
# MAIN HTML GENERATION ENGINE
# ============================================================

class HTMLGenerationEngine:
    """Main engine for HTML page generation"""

    @staticmethod
    def generate_page(title: str, description: str, style: str = "modern") -> Tuple[str, Dict[str, str]]:
        palette = ColorPaletteGenerator.generate_palette(style)
        sections = HTMLPageBuilder.extract_sections(description)
        sections_html = HTMLPageBuilder.build_sections(sections)

        css = CSSGenerator.generate(palette)

        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{title}</title>
            {css}
        </head>
        <body>
            <header>
                <h1>{title}</h1>
                <p>{description}</p>
                <button>Get Started</button>
            </header>

            <main>
                {sections_html}
            </main>
        </body>
        </html>
        """

        return html, palette

# ============================================================
# GENERATION HANDLER
# ============================================================

generation_history = []

def generate_html_page(title: str, description: str, style: str):
    if not title.strip() or not description.strip():
        return "", "❌ Please provide both title and description", ""

    try:
        html_output, palette = HTMLGenerationEngine.generate_page(title, description, style)

        color_info = f"""
        **Color Palette**
        - Primary: {palette['primary']}
        - Secondary: {palette['secondary']}
        - Accent: {palette['accent']}
        - Background: {palette['background']}
        """

        generation_history.append({
            "title": title,
            "description": description,
            "palette": palette,
            "timestamp": datetime.now().isoformat()
        })

        return html_output, color_info, "✅ Page generated successfully"

    except Exception as e:
        return "", "", f"❌ Error: {str(e)}"

# ============================================================
# GRADIO UI
# ============================================================

with gr.Blocks() as demo:
    gr.Markdown("# 🚀 HTML Quick Styler – Advanced")

    title = gr.Textbox(label="Website Title")
    description = gr.Textbox(label="Website Description", lines=3)
    style = gr.Dropdown(["modern", "creative", "minimal"], value="modern", label="Style")

    generate_btn = gr.Button("Generate Website")

    html_output = gr.HTML(label="Live Preview")
    palette_info = gr.Markdown()
    status = gr.Markdown()

    generate_btn.click(
        generate_html_page,
        inputs=[title, description, style],
        outputs=[html_output, palette_info, status]
    )

print("✅ HTML Quick Styler Advanced Ready!")
demo.launch(share=True, show_error=True, show_api=False)